name: Docker Update, Build and Publish

on:
  schedule:
    - cron: '37 7 * * *'
  workflow_dispatch:
    inputs:
      force_build:
        description: 'Force build and push the Docker image'
        required: false
        default: 'false'
      force_git_update:
        description: 'Force update the repo (for testing purposes)'
        required: false
        default: 'false'

jobs:
  check-caddy-version:
    name: Check Caddy and plugin versions
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      id-token: write
    outputs:
      updated: ${{ steps.compare-versions.outputs.updated }}
      caddy_version: ${{ steps.get-current-versions.outputs.CADDY_VERSION }}
      ovh_dns_version: ${{ steps.get-current-versions.outputs.OVH_DNS_VERSION }}
      crowdsec_bouncer_version: ${{ steps.get-current-versions.outputs.CROWDSEC_BOUNCER_VERSION }}
      maxmind_geoip_version: ${{ steps.get-current-versions.outputs.MAXMIND_GEOIP_VERSION }}
      cloudflare_version: ${{ steps.get-current-versions.outputs.CLOUDFLARE_VERSION }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get current versions from Dockerfile
        id: get-current-versions
        run: |
          CURRENT_CADDY_VERSION=$(grep -oP '(?<=ARG CADDY_VERSION=)[^ ]+' Dockerfile)
          CURRENT_OVH_DNS_VERSION=$(grep -oP '(?<=ARG OVH_DNS_VERSION=)[^ ]+' Dockerfile)
          CURRENT_CROWDSEC_BOUNCER_VERSION=$(grep -oP '(?<=ARG CROWDSEC_BOUNCER_VERSION=)[^ ]+' Dockerfile)
          CURRENT_MAXMIND_GEOIP_VERSION=$(grep -oP '(?<=ARG MAXMIND_GEOIP_VERSION=)[^ ]+' Dockerfile)
          CURRENT_CLOUDFLARE_VERSION=$(grep -oP '(?<=ARG CLOUDFLARE_VERSION=)[^ ]+' Dockerfile)
          echo "CURRENT_CADDY_VERSION=$CURRENT_CADDY_VERSION" >> $GITHUB_ENV
          echo "CURRENT_OVH_DNS_VERSION=$CURRENT_OVH_DNS_VERSION" >> $GITHUB_ENV
          echo "CURRENT_CROWDSEC_BOUNCER_VERSION=$CURRENT_CROWDSEC_BOUNCER_VERSION" >> $GITHUB_ENV
          echo "CURRENT_MAXMIND_GEOIP_VERSION=$CURRENT_MAXMIND_GEOIP_VERSION" >> $GITHUB_ENV
          echo "CURRENT_CLOUDFLARE_VERSION=$CURRENT_CLOUDFLARE_VERSION" >> $GITHUB_ENV
          echo "CADDY_VERSION=$CURRENT_CADDY_VERSION" >> $GITHUB_OUTPUT
          echo "OVH_DNS_VERSION=$CURRENT_OVH_DNS_VERSION" >> $GITHUB_OUTPUT
          echo "CROWDSEC_BOUNCER_VERSION=$CURRENT_CROWDSEC_BOUNCER_VERSION" >> $GITHUB_OUTPUT
          echo "MAXMIND_GEOIP_VERSION=$CURRENT_MAXMIND_GEOIP_VERSION" >> $GITHUB_OUTPUT
          echo "CLOUDFLARE_VERSION=$CURRENT_CLOUDFLARE_VERSION" >> $GITHUB_OUTPUT

      - name: Get latest versions
        id: get-latest-versions
        run: |
          LATEST_CADDY_VERSION=$(curl -s https://api.github.com/repos/caddyserver/caddy/tags | grep -oP '"name": "\K(.*)(?=")' | head -n1)
          LATEST_CADDY_VERSION=${LATEST_CADDY_VERSION#v}
          LATEST_OVH_DNS_VERSION=$(curl -s https://api.github.com/repos/caddy-dns/ovh/tags | grep -oP '"name": "\K(.*)(?=")' | head -n1)
          LATEST_OVH_DNS_VERSION=${LATEST_OVH_DNS_VERSION#v}
          LATEST_CROWDSEC_BOUNCER_VERSION=$(curl -s https://api.github.com/repos/hslatman/caddy-crowdsec-bouncer/tags | grep -oP '"name": "\K(.*)(?=")' | head -n1)
          LATEST_CROWDSEC_BOUNCER_VERSION=${LATEST_CROWDSEC_BOUNCER_VERSION#v}
          LATEST_MAXMIND_GEOIP_VERSION=$(curl -s https://api.github.com/repos/porech/caddy-maxmind-geolocation/tags | grep -oP '"name": "\K(.*)(?=")' | head -n1)
          LATEST_MAXMIND_GEOIP_VERSION=${LATEST_MAXMIND_GEOIP_VERSION#v}
          LATEST_CLOUDFLARE_VERSION=$(curl -s https://api.github.com/repos/caddy-dns/cloudflare/tags | grep -oP '"name": "\K(.*)(?=")' | head -n1)
          LATEST_CLOUDFLARE_VERSION=${LATEST_CLOUDFLARE_VERSION#v}
          echo "LATEST_CADDY_VERSION=$LATEST_CADDY_VERSION" >> $GITHUB_ENV
          echo "LATEST_OVH_DNS_VERSION=$LATEST_OVH_DNS_VERSION" >> $GITHUB_ENV
          echo "LATEST_CROWDSEC_BOUNCER_VERSION=$LATEST_CROWDSEC_BOUNCER_VERSION" >> $GITHUB_ENV
          echo "LATEST_MAXMIND_GEOIP_VERSION=$LATEST_MAXMIND_GEOIP_VERSION" >> $GITHUB_ENV
          echo "LATEST_CLOUDFLARE_VERSION=$LATEST_CLOUDFLARE_VERSION" >> $GITHUB_ENV

      - name: Compare versions and update Dockerfile if needed
        id: compare-versions
        run: |
          source $GITHUB_ENV
          UPDATED=false
          if [ "$CURRENT_CADDY_VERSION" != "$LATEST_CADDY_VERSION" ]; then
            sed -i "s/ARG CADDY_VERSION=$CURRENT_CADDY_VERSION/ARG CADDY_VERSION=$LATEST_CADDY_VERSION/" Dockerfile
            UPDATED=true
          fi
          if [ "$CURRENT_OVH_DNS_VERSION" != "$LATEST_OVH_DNS_VERSION" ]; then
            sed -i "s/ARG OVH_DNS_VERSION=$CURRENT_OVH_DNS_VERSION/ARG OVH_DNS_VERSION=$LATEST_OVH_DNS_VERSION/" Dockerfile
            UPDATED=true
          fi
          if [ "$CURRENT_CROWDSEC_BOUNCER_VERSION" != "$LATEST_CROWDSEC_BOUNCER_VERSION" ]; then
            sed -i "s/ARG CROWDSEC_BOUNCER_VERSION=$CURRENT_CROWDSEC_BOUNCER_VERSION/ARG CROWDSEC_BOUNCER_VERSION=$LATEST_CROWDSEC_BOUNCER_VERSION/" Dockerfile
            UPDATED=true
          fi
          if [ "$CURRENT_MAXMIND_GEOIP_VERSION" != "$LATEST_MAXMIND_GEOIP_VERSION" ]; then
            sed -i "s/ARG MAXMIND_GEOIP_VERSION=$CURRENT_MAXMIND_GEOIP_VERSION/ARG MAXMIND_GEOIP_VERSION=$LATEST_MAXMIND_GEOIP_VERSION/" Dockerfile
            UPDATED=true
          fi
          if [ "$CURRENT_CLOUDFLARE_VERSION" != "$LATEST_CLOUDFLARE_VERSION" ]; then
            sed -i "s/ARG CLOUDFLARE_VERSION=$CURRENT_CLOUDFLARE_VERSION/ARG CLOUDFLARE_VERSION=$LATEST_CLOUDFLARE_VERSION/" Dockerfile
            UPDATED=true
          fi
          echo "updated=$UPDATED" >> $GITHUB_OUTPUT

      - name: Commit & Push changes
        uses: actions-js/push@master
        if: steps.compare-versions.outputs.updated == 'true'
        with:
          branch: main
          message: 'Update Dockerfile with latest Caddy and plugin versions'
          github_token: ${{ secrets.GITHUB_TOKEN }}

  build-and-push-docker-image:
    name: Build Docker image and push to GitHub Container Registry
    runs-on: ubuntu-latest
    needs: check-caddy-version
    if: needs.check-caddy-version.outputs.updated == 'true' || (github.event_name == 'workflow_dispatch' && github.event.inputs.force_build == 'true')
    env:
      CADDY_VERSION: ${{ needs.check-caddy-version.outputs.caddy_version }}
      OVH_DNS_VERSION: ${{ needs.check-caddy-version.outputs.ovh_dns_version }}
      CROWDSEC_BOUNCER_VERSION: ${{ needs.check-caddy-version.outputs.crowdsec_bouncer_version }}
      MAXMIND_GEOIP_VERSION: ${{ needs.check-caddy-version.outputs.maxmind_geoip_version }}
      CLOUDFLARE_VERSION: ${{ needs.check-caddy-version.outputs.cloudflare_version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set lowercase repository name
        run: |
          REPO_LOWER=$(echo $GITHUB_REPOSITORY | tr '[:upper:]' '[:lower:]')
          echo "REPO_LC=$REPO_LOWER" >> $GITHUB_ENV

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v5
        env:
          REPO_LC: ${{ env.REPO_LC }}
        with:
          provenance: false
          context: .
          platforms: linux/amd64,linux/arm64/v8
          push: ${{ github.event_name != 'pull_request' }}
          file: Dockerfile
          tags: |
            ghcr.io/${{ env.REPO_LC }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            CADDY_VERSION=${{ env.CADDY_VERSION }}
            OVH_DNS_VERSION=${{ env.OVH_DNS_VERSION }}
            CROWDSEC_BOUNCER_VERSION=${{ env.CROWDSEC_BOUNCER_VERSION }}
            MAXMIND_GEOIP_VERSION=${{ env.MAXMIND_GEOIP_VERSION }}
            CLOUDFLARE_VERSION=${{ env.CLOUDFLARE_VERSION }}

      - name: Image digest
        run: echo ${{ steps.build-and-push.outputs.digest }}
