name: Docker Build and Publish

on:
  schedule:
    - cron: '37 7 * * *'
  push:
    branches: [ "main" ]
    paths-ignore:
      - '**/README.md'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - '**/README.md'
  workflow_dispatch:

env:
  # Non dichiariamo più IMAGE_NAME qui, lo calcoliamo in lowercase più avanti.

jobs:
  build-and-push-docker-image:
    name: Build Docker image and push to GitHub Container Registry
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      # serve per l’identity challenge di sigstore/fulcio se necessario
      id-token: write

    steps:
      # 1) Checkout del codice
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2) Convertiamo GITHUB_REPOSITORY in minuscolo e lo salviamo in REPO_LC (senza includere virgolette)
      - name: Set lowercase repository name
        run: |
          REPO_LOWER=$(echo $GITHUB_REPOSITORY | tr '[:upper:]' '[:lower:]')
          echo "REPO_LC=$REPO_LOWER" >> $GITHUB_ENV

      # 3) Setup di Docker Buildx
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3

      # 4) Login a GitHub Container Registry (skippa nelle PR)
      - name: Login to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 5) Build e push dell'immagine su GHCR (solo se non è una PR)
      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v5
        with:
          provenance: false
          context: .
          platforms: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ghcr.io/${{ env.REPO_LC }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # 6) Stampiamo il digest
      - name: Image digest
        run: echo ${{ steps.build-and-push.outputs.digest }}
