name: Docker Build and Publish

on:
  schedule:
    - cron: '37 7 * * *'
  push:
    branches: [ "main" ]
    paths-ignore:
      - '**/README.md'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - '**/README.md'
  workflow_dispatch:

env:
  ## (NON più) IMAGE_NAME: ${{ github.repository }}
  ## Invece di impostare direttamente IMAGE_NAME, lo ricaviamo in un passo successivo.

jobs:
  ## define job to build and publish docker image
  build-and-push-docker-image:
    name: Build Docker image and push to DockerHub and GitHub Container Registry
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      ## Used to complete the identity challenge with sigstore/fulcio when running outside of PRs.
      id-token: write

    steps:
      # 1) Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2) Convert GITHUB_REPOSITORY to lowercase and save it in REPO_LC
      - name: Set lowercase repository name
        run: |
          echo "REPO_LC=$(echo \"$GITHUB_REPOSITORY\" | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      # 3) Setup Docker buildx
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3

      # 4) Login to Docker Hub (skip on PRs)
      - name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 5) Login to GitHub Container Registry (skip on PRs)
      - name: Login to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 6) Build and push Docker image
      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v5
        with:
          provenance: false
          context: .
          platforms: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            docker.io/${{ env.REPO_LC }}:latest
            ghcr.io/${{ env.REPO_LC }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # 7) Show image digest
      - name: Image digest
        run: echo ${{ steps.build-and-push.outputs.digest }}
